
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
         lblInput.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            updateConversionResult();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            updateConversionResult();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            updateConversionResult();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInput = new javax.swing.JTextField();
        lblHasil = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCelcius = new javax.swing.JRadioButton();
        btnReamur = new javax.swing.JRadioButton();
        btnFahrenheit = new javax.swing.JRadioButton();
        btnKelvin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Konversi Suhu");
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Haikal Aditya Rahmmatullah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Input Nilai");
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Hasil Konversi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        lblInput.setName("txtNCelcius"); // NOI18N
        lblInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblInputActionPerformed(evt);
            }
        });
        lblInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblInputKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(lblInput, gridBagConstraints);

        lblHasil.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(lblHasil, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jComboBox1, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jButton1, gridBagConstraints);

        jLabel3.setText("Pilih Jenis Nilai");
        jLabel3.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Pilih Jenis Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aplikasi Konversi Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel5, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(btnCelcius);
        btnCelcius.setText("Celcius");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnCelcius, gridBagConstraints);

        buttonGroup1.add(btnReamur);
        btnReamur.setText("Reamur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnReamur, gridBagConstraints);

        buttonGroup1.add(btnFahrenheit);
        btnFahrenheit.setText("Fahrenheit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnFahrenheit, gridBagConstraints);

        buttonGroup1.add(btnKelvin);
        btnKelvin.setText("Kelvin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnKelvin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
        double inputSuhu = Double.parseDouble(lblInput.getText());
        String scale = (String) jComboBox1.getSelectedItem();
        double result = 0.0;

        if (btnCelcius.isSelected()) {
            // Konversi ke Celcius dari skala asal
            result = convertToCelcius(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f °C", result));
        } else if (btnKelvin.isSelected()) {
            // Konversi ke Kelvin dari skala asal
            result = convertToKelvin(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f K", result));
        } else if (btnReamur.isSelected()) {
            // Konversi ke Reamur dari skala asal
            result = convertToReamur(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f °Ré", result));
        } else if (btnFahrenheit.isSelected()) {
            // Konversi ke Fahrenheit dari skala asal
            result = convertToFahrenheit(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f °F", result));
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Masukkan nilai suhu yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void lblInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblInputActionPerformed

    }//GEN-LAST:event_lblInputActionPerformed

    private void lblInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblInputKeyTyped
        char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '.') {
        evt.consume();  // Hanya menerima angka dan titik desimal
    }
    }//GEN-LAST:event_lblInputKeyTyped

    //Proses Konversi
    private double convertToCelcius(double suhu, String scale) {
    switch (scale) {
        case "Kelvin":
            return suhu - 273.15;
        case "Reamur":
            return suhu * 5/4;
        case "Fahrenheit":
            return (suhu - 32) * 5/9;
        default:
            return suhu; // Sudah dalam Celcius
    }
    }

    private double convertToKelvin(double suhu, String scale) {
    switch (scale) {
        case "Celcius":
            return suhu + 273.15;
        case "Reamur":
            return (suhu * 5/4) + 273.15;
        case "Fahrenheit":
            return (suhu - 32) * 5/9 + 273.15;
        default:
            return suhu; // Sudah dalam Kelvin
    }
    }

    private double convertToReamur(double suhu, String scale) {
    switch (scale) {
        case "Celcius":
            return suhu * 4/5;
        case "Kelvin":
            return (suhu - 273.15) * 4/5;
        case "Fahrenheit":
            return (suhu - 32) * 4/9;
        default:
            return suhu; // Sudah dalam Reamur
    }
    }

    private double convertToFahrenheit(double suhu, String scale) {
    switch (scale) {
        case "Celcius":
            return (suhu * 9/5) + 32;
        case "Kelvin":
            return (suhu - 273.15) * 9/5 + 32;
        case "Reamur":
            return (suhu * 9/4) + 32;
        default:
            return suhu; // Sudah dalam Fahrenheit
    }
    }
    //tutup
    
    //Proses Implementasi konversi otomatis saat nilai input berubah
    private void updateConversionResult() {
    try {
        double inputSuhu = Double.parseDouble(lblInput.getText());
        String scale = (String) jComboBox1.getSelectedItem();
        double result = 0.0;

        if (btnCelcius.isSelected()) {
            result = convertToCelcius(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f °C", result));
        } else if (btnKelvin.isSelected()) {
            result = convertToKelvin(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f K", result));
        } else if (btnReamur.isSelected()) {
            result = convertToReamur(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f °Ré", result));
        } else if (btnFahrenheit.isSelected()) {
            result = convertToFahrenheit(inputSuhu, scale);
            lblHasil.setText(String.format("%.2f °F", result));
        }
    } catch (NumberFormatException ex) {
        // Jika input kosong atau tidak valid, kosongkan semua label hasil
        lblHasil.setText("");
    }
}   
    //tutup
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCelcius;
    private javax.swing.JRadioButton btnFahrenheit;
    private javax.swing.JRadioButton btnKelvin;
    private javax.swing.JRadioButton btnReamur;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lblHasil;
    private javax.swing.JTextField lblInput;
    // End of variables declaration//GEN-END:variables
}
